export const GET_ALL_CINEMA = "GET_ALL_CINEMA";
export const GET_LIST_CINEMA_CLUSTERS = "GET_LIST_CINEMA_CLUSTERS";
export const SELECT_CINEMA = "SELECT_CINEMA";
export const GET_SHOW_TIMES = "GET_SHOW_TIMES";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const SELECT_MOVIE_TICKET = "SELECT_MOVIE_TICKET";
export const GET_SHOWTIME_ID = "GET_SHOWTIME_ID";

